[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[dependencies]

[workspace]
members = [
    "shared_lib",
    "day-1",
    "day-2",
    "day-3",
    "day-4",
    "day-5",
    "day-6",
    "day-7",
    "day-8",
]
