[package]
name = "day-10"
version = "0.1.0"
edition = "2021"

[lib]
name = "utils"
path = "../shared_lib/src/lib.rs"

[[bin]]
name = "day-10"
path = "src/main.rs"

[dependencies]
ndarray = "0.16.1"

[features]
debug = []
