[package]
name = "day-11"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
name = "utils"
path = "../shared_lib/src/lib.rs"

[[bin]]
name = "day-10"
path = "src/main.rs"

[features]
debug = []
