[package]
name = "day-18"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"
regex = "1.11.1"
pathfinding = "4.13.0"

[lib]
name = "utils"
path = "../src/lib.rs"

[[bin]]
name = "day-18"
path = "src/main.rs"

[features]
debug = []
