[package]
name = "day-12"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.16.1"

[lib]
name = "utils"
path = "../src/lib.rs"

[[bin]]
name = "day-12"
path = "src/main.rs"

[features]
debug = []
blocking = []
